ARG POSTGRES_USER
ARG DATABASE_HOST

FROM node:18.14.0-alpine3.17
RUN apk update && apk add postgresql

WORKDIR /app/
COPY ./src/ .
RUN npm install -g npm@9.3.1
RUN cd /app/ && chmod +x ./init.sh
EXPOSE 3000/tcp
ENTRYPOINT [ "sh", "init.sh" ]
CMD [ "npm", "run", "start:dev" ]