#frontend

# Use an official Node runtime as a parent image
FROM node:18.14.0-alpine3.17


# Set the working directory to /app
WORKDIR /app/

RUN npm install -g npm@9.3.1

EXPOSE 5173

# Copy the current directory contents into the container at /app
COPY . /app/

# RUN npm install -g vite

COPY ./init.sh /app/init.sh

ENTRYPOINT [ "sh", "init.sh" ]

CMD ["npm", "run", "dev"]
