#frontend

# Use an official Node runtime as a parent image
FROM node

# Set the working directory to /app
WORKDIR /app/


EXPOSE 5173

# Copy the current directory contents into the container at /app
COPY . /app/

# RUN npm install -g vite

COPY ./init.sh /app/init.sh

ENTRYPOINT [ "sh", "init.sh" ]

CMD ["npm", "run",  "dev"]
